### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by 0x2b3bfa0** [OverlappingElvis/blob-opera-midi#1]
I've been doing some experiments for including real lyrics: https://github.com/0x2b3bfa0/blob-opera

**Comment by 0x2b3bfa0** [comment]
You've starred my project and are aware of its existence; closing this issue.

**Comment by OverlappingElvis** [comment]
Thanks for letting me know about this @0x2b3bfa0 , your implementation is really cool!

**Comment by 0x2b3bfa0** [comment]
🔔   @OverlappingElvis, if wou want to take a look now...  🎉   It's in PyPi, has some documentation and interesting options like automated upload/download and reverse conversion (Blob Opera to MusicXML).
