### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by moongazer07** [OverlappingElvis/blob-opera-midi#11]
im on chromebook and i installed linux so how could i use linux to install the midi tool

**Comment by OverlappingElvis** [comment]
Follow the instructions on https://nodejs.org/en/download/package-manager/ to install Node for your distribution, then do `npm install -g blob-opera-midi` to install it globally. Depending on how your permissions are set up, you may need to `sudo` the install for it to work. Good luck!
