### ISSUE TITLE
Export button not working on windows 10

### ISSUE THREAD

**Issue by Firman95** [OverlappingElvis/blob-opera-midi#7]
Clicking Export text doesn't work on windows terminal. I tried with powershell as well.

Please make a hotkey to export in case clicking the export button doesn't work in some terminals.

**Comment by OverlappingElvis** [comment]
Ah, that's terrible! Yes, let's get a hotkey going there. The UI could really use some love but since this started as a quick hack...

**Comment by OverlappingElvis** [comment]
@Firman95 I've added the `ctrl-e` hotkey to export and quit. Can you grab the latest on npm and let me know if this works?

**Comment by Firman95** [comment]
Now it works! Thank you!
